---

- name: Reload Apache
  shell: service apache2 reload
  when: ansible_facts['os_family'] == "Debian"

- name: Reload Apache (RedHat)
  shell: /usr/sbin/httpd -k graceful
  when: ansible_facts['os_family'] == "RedHat"

- name: Restart Apache
  shell: service apache2 restart
  when: ansible_facts['os_family'] == "Debian"
